; Draw the tree illustrating the process generated by the count-change procedure 
; of section 1.2.2 in making change for 11 cents.

; TODO

(count-change 11)
(cc 11 5)
(+ (cc 11 (- 5 1)) (cc (- 11 50) 5))
(+ (cc 11 4) (cc -39 5))
(+ (cc 11 4) (cc -39 5))
(+ (+ (cc 11 3) (cc (- 11 25) 4)) (0))
(+ (cc 11 3) (cc -14 4))
(+ (+ (cc 11 2) (cc (- 11 10) 3)) (0))
(+ (cc 11 2) (cc 1 3))
;  |       | \      \
;  |       |  -------------------\--------------------------\
;  \-------\-------------------\ |                          |
(+ (+ (cc 11 1) (cc (- 11 5) 2)) (+ (cc 1 2) (cc (- 1 10) 3)))
(+ (+ (cc 11 1) (cc 6 2))        (+ (cc 1 2) (cc -9 3)))
(+ (+ (cc 11 1) (cc 6 2))        (+ (cc 1 2) 0))
(+ (cc 11 1) (cc 6 2) (cc 1 2))
